package uz.silkStep.project.dto.response.pub;

import lombok.*;

import java.time.Instant;

@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PublicAIChatResponse {
    private String message;
    private String destinationSlug;
    private Instant timestamp;
}

// PublicAIChatResponse → represents a response DTO for AI chat interactions, containing fields for the message generated by the AI, an optional slug for a related destination, and a timestamp indicating when the response was created. This class is typically used to return AI-generated responses in API calls related to chat functionality.